name: Build and Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
            uses: actions/checkout@v2

        - name: Setup .NET
            uses: actions/setup-dotnet@v2
            with:
                dotnet-version: '6.0.x'

        - name: Restore dependencies
            run: dotnet restore

        - name: Build bleak.Api.Rest
            run: dotnet build --configuration Release --project bleak.Api.Rest

        - name: Build bleak.Api.Rest.Tests
            run: dotnet build --configuration Release --project bleak.Api.Rest.Tests

        - name: Run unit tests
            run: dotnet test --no-build --verbosity normal --project bleak.Api.Rest.Tests

        - name: Publish package
            run: dotnet pack --configuration Release --output ./nupkg
            env:
                NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

        - name: Push package to NuGet
            run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json