# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
#  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '12'
  Patch: '0'


steps:
- script: |
    dotnet restore bleak.Api.Rest.Common/bleak.Api.Rest.Common.csproj
    dotnet restore bleak.Api.Rest.Common.Tests/bleak.Api.Rest.Common.Tests.csproj
    dotnet restore bleak.Api.Rest/bleak.Api.Rest.csproj
    dotnet restore bleak.Api.Rest.Tests/bleak.Api.Rest.Tests.csproj
    dotnet build bleak.Api.Rest.Common/bleak.Api.Rest.Common.csproj --configuration $(buildConfiguration)
    dotnet build bleak.Api.Rest.Common.Tests/bleak.Api.Rest.Common.Tests.csproj --configuration $(buildConfiguration)
    dotnet build bleak.Api.Rest/bleak.Api.Rest.csproj --configuration $(buildConfiguration)
    dotnet build bleak.Api.Rest.Tests/bleak.Api.Rest.Tests.csproj --configuration $(buildConfiguration)
    dotnet test bleak.Api.Rest.Common.Tests --configuration $(buildConfiguration) --logger trx
    dotnet test bleak.Api.Rest.Tests --configuration $(buildConfiguration) --logger trx
    dotnet pack bleak.Api.Rest.Common/bleak.Api.Rest.Common.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
    dotnet pack bleak.Api.Rest/bleak.Api.Rest.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGetConnection'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
