# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016'
#  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    dotnet restore bleak.Api.Rest/bleak.Api.Rest.csproj
    dotnet restore bleak.Api.Rest.NetFrameworkTests/bleak.Api.Rest.NetFrameworkTests.csproj
    dotnet restore bleak.Api.Rest.Tests/bleak.Api.Rest.Tests.csproj
    dotnet restore bleak.Api.Json/bleak.Api.Json.csproj
    dotnet restore bleak.Api.Json.Tests/bleak.Api.Json.Tests.csproj
    dotnet restore bleak.Api.Rest.Common/bleak.Api.Rest.Common.csproj
    dotnet restore bleak.Api.Rest.Common.Core.Tests/bleak.Api.Rest.Common.Core.Tests.csproj
    dotnet restore bleak.Api.Rest.Common.NetFramework.Tests/bleak.Api.Rest.Common.NetFramework.Tests.csproj
    dotnet restore bleak.Api.Rest.Core/bleak.Api.Rest.Core.csproj
    dotnet restore bleak.Api.Rest.Core.Tests/bleak.Api.Rest.Core.Tests.csproj
    dotnet restore bleak.Api.Rest.Portable/bleak.Api.Rest.Portable.csproj
    dotnet build \.\bleak.Api.OnlyCore.sln' --configuration $(buildConfiguration)
	dotnet test bleak.Api.Json.Tests --configuration $(buildConfiguration) --logger trx
    dotnet test bleak.Api.Rest.Core.Tests --configuration $(buildConfiguration) --logger trx
    dotnet test bleak.Api.Rest.Common.Core.Tests --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1