# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Read version.txt
      id: version
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

    - name: Generate build number
      id: build-number
      run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Set full version
      id: set-version
      run: echo "FULL_VERSION=${VERSION}.${BUILD_NUMBER}" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Pack bleak.Api.Rest
      run: dotnet pack --configuration Release /p:Version=${FULL_VERSION} bleak.Api.Rest --output ./nupkg
    
    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json